"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from config.runtime_profile import detect_runtime_profile

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일 로드
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$bbc&i-r1gt#kcyf!*4=hdb_c+30k7ef#h!^@!&70b$f=cg!v1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

DEFAULT_ALLOWED_HOSTS = ['jakesto.synology.me', 'localhost', '127.0.0.1']
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', ','.join(DEFAULT_ALLOWED_HOSTS)).split(',')
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'https://jakesto.synology.me,http://localhost,http://127.0.0.1',
    ).split(',')
    if origin.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise 미들웨어
    'config.db_routing.HostDatabaseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DB 호스트 결정
# - DB_HOST_MODE=local: 로컬 DB(192.168.0.107) 강제
# - DB_HOST_MODE=nas: NAS DB(192.168.0.250) 강제
# - 미지정: 머신 프로필 자동 감지(local/nas)
runtime_profile = detect_runtime_profile()
db_host_mode = os.environ.get('DB_HOST_MODE', '').strip().lower() or runtime_profile
LOCAL_DB_HOST = os.environ.get('MARIADB_LOCAL_HOST', '192.168.0.107')
NAS_DB_HOST = os.environ.get('MARIADB_NAS_HOST', '192.168.0.250')

if db_host_mode == 'local':
    DEFAULT_DB_HOST = LOCAL_DB_HOST
elif db_host_mode == 'nas':
    DEFAULT_DB_HOST = NAS_DB_HOST
elif DEBUG:
    DEFAULT_DB_HOST = LOCAL_DB_HOST
else:
    DEFAULT_DB_HOST = NAS_DB_HOST

db_name = os.environ.get('MARIADB_NAME', 'sc_garden')
db_user = os.environ.get('MARIADB_USER', 'sc_garden_user')
db_password = os.environ.get('MARIADB_PASSWORD', 'Sc_Garden!2026')
db_port = os.environ.get('MARIADB_PORT', '3306')

db_common = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': db_name,
    'USER': db_user,
    'PASSWORD': db_password,
    'PORT': db_port,
    'OPTIONS': {
        'charset': 'utf8mb4',
    },
}

DATABASES = {
    'default': {
        **db_common,
        'HOST': os.environ.get('MARIADB_HOST', DEFAULT_DB_HOST),
    },
    'local': {
        **db_common,
        'HOST': LOCAL_DB_HOST,
    },
    'nas': {
        **db_common,
        'HOST': NAS_DB_HOST,
    }
}

DATABASE_ROUTERS = ['config.db_routing.HostDatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise 설정 (프로덕션에서 정적 파일 압축 및 캐시)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 만약 이전에 만든 static 폴더가 따로 있다면 아래와 같이 추가할 수 있습니다.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Login redirect URL
LOGIN_REDIRECT_URL = 'portfolio:management'